services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nintendin
    ports:
      - "5432:5432"
    volumes:
      #- ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: backend
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - "8080:8080"
    restart: always
    command: npm run dev
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: nintendin
    depends_on:
      - postgres

volumes:
  postgres_data:
