services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend_prod
    working_dir: /app
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    command: npm run start:prod
    environment:
      NODE_ENV: production
    depends_on:
      - postgres

volumes:
  postgres_data_prod: