version: '3.8'

services:
  mobile-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: nintendin-mobile
    ports:
      - "19006:19006"  # Expo DevTools
      - "19001:19001"  # Expo debugging
      - "19002:19002"  # Expo debugging  
      - "8081:8081"    # Metro bundler
    volumes:
      # Bind mount source code for hot reload during development
      - .:/opt/app
      - /opt/app/node_modules
      # Bind mount for expo cache
      - expo-cache:/home/node/.expo
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.130
    networks:
      - retro-games-network
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  expo-cache:

networks:
  retro-games-network:
    external: true
    # If the network doesn't exist, create it first with:
    # docker network create retro-games-network
